[versions]
# --- [PLUGINS & TOOLS] ---
java = "17"
kotlin = "2.1.21"
springBoot = "3.5.10"
springDependencyManagement = "1.1.7"
ksp = "2.1.21-2.0.2"
jacoco = "0.8.14"
sonarqube = "7.2.2.6593"

# --- [MAIN DEPENDENCIES] ---
jacksonDatabind = "3.0.2"
kotlinLogging = "7.0.13"
springDocOpenApi = "2.8.13"
querydsl = "7.1"
p6spy = "1.12.0"
redisson = "3.52.0"

# --- [TEST DEPENDENCIES] ---
mockK = "1.14.5"
autoParams = "11.3.1"
fixtureMonkey = "1.1.15"
datafaker = "2.5.1"
jqwik = "1.9.3"
awaitility = "4.3.0"
embeddedRedis = "1.4.3"

[libraries]
## --- [SPRING BOOT BOM] ---
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "springBoot" }

## --- [SPRING ECOSYSTEM - CORE & DX] ---
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-cache = { module = "org.springframework.boot:spring-boot-starter-cache" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-devtools = { module = "org.springframework.boot:spring-boot-devtools" }
spring-boot-docker-compose = { module = "org.springframework.boot:spring-boot-docker-compose" }
spring-boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor" }
# Kotlin
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin" }

## --- [DATABASE & PERSISTENCE] ---
# Starters & Frameworks
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-starter-data-redis = { module = "org.springframework.boot:spring-boot-starter-data-redis" }
# Querydsl
querydsl-jpa = { module = "io.github.openfeign.querydsl:querydsl-jpa", version.ref = "querydsl" }
querydsl-apt = { module = "io.github.openfeign.querydsl:querydsl-apt", version.ref = "querydsl" }
querydsl-ksp-codegen = { module = "io.github.openfeign.querydsl:querydsl-ksp-codegen", version.ref = "querydsl" }
# Logging & Proxy
kotlin-logging-jvm = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlinLogging" }
p6spy-spring-boot-starter = { module = "com.github.gavlyukovskiy:p6spy-spring-boot-starter", version.ref = "p6spy" }
# Drivers
h2 = { module = "com.h2database:h2" }
mysql-connector-j = { module = "com.mysql:mysql-connector-j" }
# Redis Client
redisson = { module = "org.redisson:redisson", version.ref = "redisson" }
redisson-spring-boot-starter = { module = "org.redisson:redisson-spring-boot-starter", version.ref = "redisson" }
redisson-spring-data = { module = "org.redisson:redisson-spring-data-35", version.ref = "redisson" }

## --- [UTILITIES & API DOCS] ---
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" }
jackson-databind = { module = "tools.jackson.core:jackson-databind", version.ref = "jacksonDatabind" }
springdoc-openapi-starter-webmvc-ui = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springDocOpenApi" }

## --- [TESTING UTILS & FRAMEWORKS] ---
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }
mockk = { module = "io.mockk:mockk", version.ref = "mockK" }
# Random Data & Property Testing
autoparams = { module = "io.github.autoparams:autoparams", version.ref = "autoParams" }
autoparams-lombok = { module = "io.github.autoparams:autoparams-lombok", version.ref = "autoParams" }
autoparams-mockito = { module = "io.github.autoparams:autoparams-mockito", version.ref = "autoParams" }
fixture-monkey-autoparams = { module = "com.navercorp.fixturemonkey:fixture-monkey-autoparams", version.ref = "fixtureMonkey" }
fixture-monkey-datafaker = { module = "com.navercorp.fixturemonkey:fixture-monkey-datafaker", version.ref = "fixtureMonkey" }
fixture-monkey-jackson = { module = "com.navercorp.fixturemonkey:fixture-monkey-jackson", version.ref = "fixtureMonkey" }
fixture-monkey-javax-validation = { module = "com.navercorp.fixturemonkey:fixture-monkey-javax-validation", version.ref = "fixtureMonkey" }
fixture-monkey-kotlin = { module = "com.navercorp.fixturemonkey:fixture-monkey-kotlin", version.ref = "fixtureMonkey" }
fixture-monkey-mockito = { module = "com.navercorp.fixturemonkey:fixture-monkey-mockito", version.ref = "fixtureMonkey" }
fixture-monkey-starter = { module = "com.navercorp.fixturemonkey:fixture-monkey-starter", version.ref = "fixtureMonkey" }
datafaker = { module = "net.datafaker:datafaker", version.ref = "datafaker" }
jqwik = { module = "net.jqwik:jqwik", version.ref = "jqwik" }
jqwik-api = { module = "net.jqwik:jqwik-api", version.ref = "jqwik" }
jqwik-engine = { module = "net.jqwik:jqwik-engine", version.ref = "jqwik" }
jqwik-kotlin = { module = "net.jqwik:jqwik-kotlin", version.ref = "jqwik" }
jqwik-time = { module = "net.jqwik:jqwik-time", version.ref = "jqwik" }
jqwik-testing = { module = "net.jqwik:jqwik-testing", version.ref = "jqwik" }
# Others
awaitility = { module = "org.awaitility:awaitility", version.ref = "awaitility" }
embedded-redis = { module = "com.github.codemonstur:embedded-redis", version.ref = "embeddedRedis" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

[bundles]
redisson = ["redisson", "redisson-spring-boot-starter", "redisson-spring-data"]
autoparams = ["autoparams", "autoparams-lombok", "autoparams-mockito"]
fixture-monkey = ["fixture-monkey-autoparams", "fixture-monkey-datafaker", "fixture-monkey-jackson", "fixture-monkey-javax-validation", "fixture-monkey-kotlin", "fixture-monkey-mockito", "fixture-monkey-starter"]
jqwik = ["jqwik", "jqwik-api", "jqwik-engine", "jqwik-kotlin", "jqwik-time", "jqwik-testing"]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }
kotlin-plugin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }